# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=ez80 -run-pass=postrapseudos -o - %s | FileCheck %s

# Check O16/O24 source handling for Cmp16a0/Cmp24a0 pseudo expansion.
# O-reg sources should lower to:
#   SBCxxaa; ADCxxao <src>
# while HL/UHL sources should keep the generic add/or/sbc form.

---
# CHECK-LABEL: name:            cmp16a0_o16
# CHECK:       SBC16aa
# CHECK-NEXT:  ADC16ao $de
name: cmp16a0_o16
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $de
    Cmp16a0 killed $de, implicit-def $f, implicit-def dead $hl
...

---
# CHECK-LABEL: name:            cmp24a0_o24
# CHECK:       SBC24aa
# CHECK-NEXT:  ADC24ao $ude
name: cmp24a0_o24
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $ude
    Cmp24a0 killed $ude, implicit-def $f, implicit-def dead $uhl
...

---
# CHECK-LABEL: name:            cmp16a0_h16
# CHECK:       $hl = ADD16ao $hl, undef $bc
# CHECK-NEXT:  OR8ar undef $a
# CHECK-NEXT:  SBC16ao undef $bc
name: cmp16a0_h16
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $hl
    Cmp16a0 killed $hl, implicit-def $f, implicit-def dead $hl
...

---
# CHECK-LABEL: name:            cmp24a0_h24
# CHECK:       $uhl = ADD24ao $uhl, undef $ubc
# CHECK-NEXT:  OR8ar undef $a
# CHECK-NEXT:  SBC24ao undef $ubc
name: cmp24a0_h24
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $uhl
    Cmp24a0 killed $uhl, implicit-def $f, implicit-def dead $uhl
...
## NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
# CHECK: {{.*}}
