; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=z80 < %s | FileCheck %s --check-prefixes=Z80
; RUN: llc -mtriple=ez80-code16 < %s | FileCheck %s --check-prefixes=EZ80-CODE16
; RUN: llc -mtriple=ez80 < %s | FileCheck %s --check-prefixes=EZ80

define i8 @shl.i8.2(i8 %value) {
; Z80-LABEL: shl.i8.2:
; Z80:       ; %bb.0:
; Z80-NEXT:    ld iy, 0
; Z80-NEXT:    add iy, sp
; Z80-NEXT:    ld a, (iy + 2)
; Z80-NEXT:    add a, a
; Z80-NEXT:    add a, a
; Z80-NEXT:    ret
;
; EZ80-CODE16-LABEL: shl.i8.2:
; EZ80-CODE16:       ; %bb.0:
; EZ80-CODE16-NEXT:    ld iy, 0
; EZ80-CODE16-NEXT:    add iy, sp
; EZ80-CODE16-NEXT:    ld a, (iy + 2)
; EZ80-CODE16-NEXT:    add a, a
; EZ80-CODE16-NEXT:    add a, a
; EZ80-CODE16-NEXT:    ret
;
; EZ80-LABEL: shl.i8.2:
; EZ80:       ; %bb.0:
; EZ80-NEXT:    ld iy, 0
; EZ80-NEXT:    add iy, sp
; EZ80-NEXT:    ld a, (iy + 3)
; EZ80-NEXT:    add a, a
; EZ80-NEXT:    add a, a
; EZ80-NEXT:    ret
  %result = shl i8 %value, 2
  ret i8 %result
}

define i8 @ashr.i8.2(i8 %value) {
; Z80-LABEL: ashr.i8.2:
; Z80:       ; %bb.0:
; Z80-NEXT:    ld iy, 0
; Z80-NEXT:    add iy, sp
; Z80-NEXT:    ld a, (iy + 2)
; Z80-NEXT:    sra a
; Z80-NEXT:    sra a
; Z80-NEXT:    ret
;
; EZ80-CODE16-LABEL: ashr.i8.2:
; EZ80-CODE16:       ; %bb.0:
; EZ80-CODE16-NEXT:    ld iy, 0
; EZ80-CODE16-NEXT:    add iy, sp
; EZ80-CODE16-NEXT:    ld a, (iy + 2)
; EZ80-CODE16-NEXT:    sra a
; EZ80-CODE16-NEXT:    sra a
; EZ80-CODE16-NEXT:    ret
;
; EZ80-LABEL: ashr.i8.2:
; EZ80:       ; %bb.0:
; EZ80-NEXT:    ld iy, 0
; EZ80-NEXT:    add iy, sp
; EZ80-NEXT:    ld a, (iy + 3)
; EZ80-NEXT:    sra a
; EZ80-NEXT:    sra a
; EZ80-NEXT:    ret
  %result = ashr i8 %value, 2
  ret i8 %result
}

define i8 @lshr.i8.2(i8 %value) {
; Z80-LABEL: lshr.i8.2:
; Z80:       ; %bb.0:
; Z80-NEXT:    ld iy, 0
; Z80-NEXT:    add iy, sp
; Z80-NEXT:    ld a, (iy + 2)
; Z80-NEXT:    srl a
; Z80-NEXT:    srl a
; Z80-NEXT:    ret
;
; EZ80-CODE16-LABEL: lshr.i8.2:
; EZ80-CODE16:       ; %bb.0:
; EZ80-CODE16-NEXT:    ld iy, 0
; EZ80-CODE16-NEXT:    add iy, sp
; EZ80-CODE16-NEXT:    ld a, (iy + 2)
; EZ80-CODE16-NEXT:    srl a
; EZ80-CODE16-NEXT:    srl a
; EZ80-CODE16-NEXT:    ret
;
; EZ80-LABEL: lshr.i8.2:
; EZ80:       ; %bb.0:
; EZ80-NEXT:    ld iy, 0
; EZ80-NEXT:    add iy, sp
; EZ80-NEXT:    ld a, (iy + 3)
; EZ80-NEXT:    srl a
; EZ80-NEXT:    srl a
; EZ80-NEXT:    ret
  %result = lshr i8 %value, 2
  ret i8 %result
}
