; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=ez80 < %s | FileCheck %s --check-prefix=EZ80

define i8 @extract_mid_byte32(i32 %x) {
; EZ80-LABEL: extract_mid_byte32:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    ld iy, 0
; EZ80-NEXT:    add iy, sp
; EZ80-NEXT:    ld bc, (iy + 3)
; EZ80-NEXT:    ld l, 24
; EZ80-NEXT:    ld a, (iy + 6)
; EZ80-NEXT:    call __lshru
; EZ80-NEXT:    ld a, c
; EZ80-NEXT:    ret
entry:
  %shr = lshr i32 %x, 24
  %res = trunc i32 %shr to i8
  ret i8 %res
}

define i8 @extract_mid_byte48(i48 %x) {
; EZ80-LABEL: extract_mid_byte48:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    ld iy, 0
; EZ80-NEXT:    add iy, sp
; EZ80-NEXT:    ld c, 24
; EZ80-NEXT:    ld hl, (iy + 3)
; EZ80-NEXT:    ld de, (iy + 6)
; EZ80-NEXT:    call __i48shru
; EZ80-NEXT:    ld a, l
; EZ80-NEXT:    ret
entry:
  %shr = lshr i48 %x, 24
  %res = trunc i48 %shr to i8
  ret i8 %res
}

define i8 @extract_mid_byte64(i64 %x) {
; EZ80-LABEL: extract_mid_byte64:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    ld iy, 0
; EZ80-NEXT:    add iy, sp
; EZ80-NEXT:    ld hl, 24
; EZ80-NEXT:    push hl
; EZ80-NEXT:    ld hl, (iy + 3)
; EZ80-NEXT:    ld de, (iy + 6)
; EZ80-NEXT:    ld bc, (iy + 9)
; EZ80-NEXT:    ; kill: def $bc killed $bc killed $ubc
; EZ80-NEXT:    call __llshru
; EZ80-NEXT:    pop de
; EZ80-NEXT:    ld a, l
; EZ80-NEXT:    ret
entry:
  %shr = lshr i64 %x, 24
  %res = trunc i64 %shr to i8
  ret i8 %res
}
