; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=ez80 < %s | FileCheck %s

declare float @llvm.atan2.f32(float, float)
declare { double, double } @llvm.modf.f64(double)

define float @atan2f32(float %y, float %x) {
; CHECK-LABEL: atan2f32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ld iy, 0
; CHECK-NEXT:    add iy, sp
; CHECK-NEXT:    ld hl, (iy + 12)
; CHECK-NEXT:    push hl
; CHECK-NEXT:    ld hl, (iy + 9)
; CHECK-NEXT:    push hl
; CHECK-NEXT:    ld hl, (iy + 6)
; CHECK-NEXT:    push hl
; CHECK-NEXT:    ld hl, (iy + 3)
; CHECK-NEXT:    push hl
; CHECK-NEXT:    call _atan2f
; CHECK-NEXT:    ld iy, 12
; CHECK-NEXT:    add iy, sp
; CHECK-NEXT:    ld sp, iy
; CHECK-NEXT:    ret
  %result = call float @llvm.atan2.f32(float %y, float %x)
  ret float %result
}

define float @negf32(float %x) {
; CHECK-LABEL: negf32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ld iy, 0
; CHECK-NEXT:    add iy, sp
; CHECK-NEXT:    ld bc, (iy + 3)
; CHECK-NEXT:    ld a, (iy + 6)
; CHECK-NEXT:    call __fneg
; CHECK-NEXT:    push bc
; CHECK-NEXT:    pop hl
; CHECK-NEXT:    ld e, a
; CHECK-NEXT:    ret
  %result = fneg float %x
  ret float %result
}

define double @modf64(double %x, ptr %intpart) {
; CHECK-LABEL: modf64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    push ix
; CHECK-NEXT:    ld ix, 0
; CHECK-NEXT:    add ix, sp
; CHECK-NEXT:    lea hl, ix - 21
; CHECK-NEXT:    ld sp, hl
; CHECK-NEXT:    pea ix - 13
; CHECK-NEXT:    ld hl, (ix + 12)
; CHECK-NEXT:    push hl
; CHECK-NEXT:    ld hl, (ix + 9)
; CHECK-NEXT:    push hl
; CHECK-NEXT:    ld hl, (ix + 6)
; CHECK-NEXT:    push hl
; CHECK-NEXT:    call _modfl
; CHECK-NEXT:    ld (ix - 16), hl
; CHECK-NEXT:    ld (ix - 19), de
; CHECK-NEXT:    ld (ix - 21), c
; CHECK-NEXT:    ld (ix - 20), b
; CHECK-NEXT:    ld iy, 12
; CHECK-NEXT:    add iy, sp
; CHECK-NEXT:    ld sp, iy
; CHECK-NEXT:    ld bc, (ix - 13)
; CHECK-NEXT:    ld hl, (ix - 10)
; CHECK-NEXT:    ld de, (ix - 7)
; CHECK-NEXT:    ld iy, (ix + 15)
; CHECK-NEXT:    ld (iy), bc
; CHECK-NEXT:    ld (iy + 3), hl
; CHECK-NEXT:    ld (iy + 6), e
; CHECK-NEXT:    ld (iy + 7), d
; CHECK-NEXT:    ld hl, (ix - 16)
; CHECK-NEXT:    ld de, (ix - 19)
; CHECK-NEXT:    ld c, (ix - 21)
; CHECK-NEXT:    ld b, (ix - 20)
; CHECK-NEXT:    ld sp, ix
; CHECK-NEXT:    pop ix
; CHECK-NEXT:    ret
  %result = call { double, double } @llvm.modf.f64(double %x)
  %fractional = extractvalue { double, double } %result, 0
  %integral = extractvalue { double, double } %result, 1
  store double %integral, ptr %intpart
  ret double %fractional
}
