; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=ez80 -O3 -verify-machineinstrs < %s | FileCheck %s

; Register allocation can introduce spill slots after reserved registers have
; been computed. IX must already be reserved when that happens because the
; spills make it the frame pointer.

define void @frame_spill() nounwind {
; CHECK-LABEL: frame_spill:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    push ix
; CHECK-NEXT:    ld ix, 0
; CHECK-NEXT:    add ix, sp
; CHECK-NEXT:    lea hl, ix - 18
; CHECK-NEXT:    ld sp, hl
; CHECK-NEXT:    call _keep_running
; CHECK-NEXT:    add hl, bc
; CHECK-NEXT:    or a, a
; CHECK-NEXT:    sbc hl, bc
; CHECK-NEXT:    jp z, BB0_3
; CHECK-NEXT:  ; %bb.1: ; %loop.preheader
; CHECK-NEXT:    ld bc, 0
; CHECK-NEXT:    ld a, 66
; CHECK-NEXT:    ld e, b
; CHECK-NEXT:    ld iy, 2097152
; CHECK-NEXT:    ld l, 67
; CHECK-NEXT:    ld (ix - 12), hl
; CHECK-NEXT:    ld hl, -1048576
; CHECK-NEXT:    ld (ix - 15), hl
; CHECK-NEXT:    ld l, a
; CHECK-NEXT:    ld (ix - 18), hl
; CHECK-NEXT:    private BB0_2
; CHECK-NEXT:  BB0_2: ; %loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ld a, e
; CHECK-NEXT:    ld hl, -3932160
; CHECK-NEXT:    ld e, 66
; CHECK-NEXT:    call __fadd
; CHECK-NEXT:    ld (ix - 3), bc
; CHECK-NEXT:    ld l, a
; CHECK-NEXT:    ld (ix - 6), hl
; CHECK-NEXT:    lea bc, iy + 0
; CHECK-NEXT:    ld hl, (ix - 12)
; CHECK-NEXT:    ld a, l
; CHECK-NEXT:    ld iy, -1048576
; CHECK-NEXT:    lea hl, iy + 0
; CHECK-NEXT:    dec e
; CHECK-NEXT:    call __fadd
; CHECK-NEXT:    ld (ix - 9), bc
; CHECK-NEXT:    ld iyl, a
; CHECK-NEXT:    ld bc, (ix - 3)
; CHECK-NEXT:    ld hl, (ix - 6)
; CHECK-NEXT:    ld a, l
; CHECK-NEXT:    ld hl, (ix - 15)
; CHECK-NEXT:    ld de, (ix - 18)
; CHECK-NEXT:    ; kill: def $e killed $e killed $ude
; CHECK-NEXT:    call __fadd
; CHECK-NEXT:    ld e, a
; CHECK-NEXT:    ld hl, (ix - 6)
; CHECK-NEXT:    push hl
; CHECK-NEXT:    ld hl, (ix - 3)
; CHECK-NEXT:    push hl
; CHECK-NEXT:    ld hl, 65
; CHECK-NEXT:    push hl
; CHECK-NEXT:    ld hl, -1048576
; CHECK-NEXT:    push hl
; CHECK-NEXT:    ld (ix - 18), de
; CHECK-NEXT:    push de
; CHECK-NEXT:    ld (ix - 15), bc
; CHECK-NEXT:    push bc
; CHECK-NEXT:    ld (ix - 12), iy
; CHECK-NEXT:    push iy
; CHECK-NEXT:    ld hl, (ix - 9)
; CHECK-NEXT:    push hl
; CHECK-NEXT:    call _sink
; CHECK-NEXT:    ld hl, 24
; CHECK-NEXT:    add hl, sp
; CHECK-NEXT:    ld sp, hl
; CHECK-NEXT:    call _keep_running
; CHECK-NEXT:    ld iy, (ix - 9)
; CHECK-NEXT:    ld de, (ix - 6)
; CHECK-NEXT:    ld bc, (ix - 3)
; CHECK-NEXT:    add hl, bc
; CHECK-NEXT:    or a, a
; CHECK-NEXT:    sbc hl, bc
; CHECK-NEXT:    jr nz, BB0_2
; CHECK-NEXT:    private BB0_3
; CHECK-NEXT:  BB0_3: ; %exit
; CHECK-NEXT:    ld sp, ix
; CHECK-NEXT:    pop ix
; CHECK-NEXT:    ret
entry:
  %running = tail call i24 @keep_running()
  %stopped = icmp eq i24 %running, 0
  br i1 %stopped, label %exit, label %loop

loop:
  %vy = phi float [ 0.000000e+00, %entry ], [ %next.vy, %loop ]
  %x = phi float [ 1.600000e+02, %entry ], [ %next.x, %loop ]
  %y = phi float [ 1.200000e+02, %entry ], [ %next.y, %loop ]
  %next.vy = fadd fast float %vy, 9.800000e+01
  %next.x = fadd fast float %x, 3.000000e+01
  %next.y = fadd fast float %next.vy, %y
  tail call void @sink(float %next.x, float %next.y, float 3.000000e+01,
                       float %next.vy)
  %again = tail call i24 @keep_running()
  %done = icmp eq i24 %again, 0
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

declare i24 @keep_running()
declare void @sink(float, float, float, float)
