; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=ez80 -verify-machineinstrs < %s | FileCheck %s

define i24 @register_output() {
; CHECK-LABEL: register_output:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ;APP
; CHECK-NEXT:    ;NO_APP
; CHECK-NEXT:    ret
  %result = call i24 asm "", "=r"()
  ret i24 %result
}

define void @immediate_inputs() {
; CHECK-LABEL: immediate_inputs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ;APP
; CHECK-NEXT:    ; 7
; CHECK-NEXT:    assume adl = 1
; CHECK-NEXT:    ;NO_APP
; CHECK-NEXT:    ;APP
; CHECK-NEXT:    ; 42
; CHECK-NEXT:    assume adl = 1
; CHECK-NEXT:    ;NO_APP
; CHECK-NEXT:    ret
  call void asm sideeffect "; $0", "I"(i24 7)
  call void asm sideeffect "; $0", "i"(i24 42)
  ret void
}
