; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=z80 < %s | FileCheck %s
; RUN: llc -mtriple=ez80-code16 < %s | FileCheck %s
; RUN: llc -mtriple=ez80 < %s | FileCheck %s

define preserve_allcc void @generic() #0 {
; CHECK-LABEL: generic:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ei
; CHECK-NEXT:    reti
  ret void
}

define preserve_allcc void @nested() #1 {
; CHECK-LABEL: nested:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ei
; CHECK-NEXT:    reti
  ret void
}

define preserve_allcc void @nmi() #2 {
; CHECK-LABEL: nmi:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    retn
  ret void
}

attributes #0 = { "interrupt"="Generic" }
attributes #1 = { "interrupt"="Nested" }
attributes #2 = { "interrupt"="NMI" }
