; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=z80 < %s | FileCheck %s

@quoted = constant [4 x i8] c"a\22b\00"

; CHECK: _quoted:
; CHECK-NEXT: db "a\042b\000"
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
