; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=z80 < %s | FileCheck %s --check-prefix=Z80
; RUN: llc -mtriple=ez80 < %s | FileCheck %s --check-prefix=EZ80
; RUN: llc -mtriple=ez80 --z80-trap-rst-vector=56 < %s | FileCheck %s --check-prefix=EZ80-RST56

declare void @llvm.trap()
declare void @llvm.debugtrap()
declare void @llvm.ubsantrap(i8 immarg)

define void @trap_now() {
; Z80-LABEL: trap_now:
; Z80:       ; %bb.0: ; %entry
; Z80-NEXT:    rst 0
;
; EZ80-LABEL: trap_now:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    rst 0
;
; EZ80-RST56-LABEL: trap_now:
; EZ80-RST56:       ; %bb.0: ; %entry
; EZ80-RST56-NEXT:    rst 56
entry:
  call void @llvm.trap()
  unreachable
}

define void @debugtrap_now() {
; Z80-LABEL: debugtrap_now:
; Z80:       ; %bb.0: ; %entry
; Z80-NEXT:    rst 0
;
; EZ80-LABEL: debugtrap_now:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    rst 0
;
; EZ80-RST56-LABEL: debugtrap_now:
; EZ80-RST56:       ; %bb.0: ; %entry
; EZ80-RST56-NEXT:    rst 56
entry:
  call void @llvm.debugtrap()
  unreachable
}

define void @ubsantrap_now() {
; Z80-LABEL: ubsantrap_now:
; Z80:       ; %bb.0: ; %entry
; Z80-NEXT:    rst 0
;
; EZ80-LABEL: ubsantrap_now:
; EZ80:       ; %bb.0: ; %entry
; EZ80-NEXT:    rst 0
;
; EZ80-RST56-LABEL: ubsantrap_now:
; EZ80-RST56:       ; %bb.0: ; %entry
; EZ80-RST56-NEXT:    rst 56
entry:
  call void @llvm.ubsantrap(i8 7)
  unreachable
}
